apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: production 
data:
  PRODUCT_API_URL: "http://product-service.production.svc.cluster.local:8000"
  ORDER_API_URL:   "http://order-service.production.svc.cluster.local:8001"